@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Logic" LOGIC_COLOR_T1
participant ":LogicManager" as LM LOGIC_COLOR
participant ":AddressBookParser" as ABP LOGIC_COLOR
participant ":DeleteCommandParser" as DCP LOGIC_COLOR
participant "dc:DeleteCommand" as dc LOGIC_COLOR
participant "r:CommandResult" as r LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
participant "toDelete:Client" as tD MODEL_COLOR
participant "m:Model" as m MODEL_COLOR
end box

box "Storage" MODEL_COLOR_T2
participant ":Storage" as S MODEL_COLOR
end box

[-> LM: execute("del [INDEX]")
activate LM
LM -> ABP : parseCommand("del [INDEX]")
activate ABP
create DCP
ABP -> DCP ++
DCP --> ABP --
ABP -> DCP : parse("[INDEX]")
activate DCP

create tD
DCP -> tD ++
tD --> DCP --

create dc
DCP -> dc ++
dc --> DCP --
DCP --> ABP : dc
deactivate DCP
destroy DCP

ABP --> LM : dc
deactivate ABP

LM -> dc : execute(m)
activate dc
dc -> m ++ : deleteClient(toDelete)
m --> dc --

create r
dc -> r ++
r --> dc --
dc --> LM -- : r

LM -> m ++ : getAddressBook()
m --> LM -- : ab

LM -> S ++ : saveAddressBook(ab)
S -> LM --

[<- LM --
@enduml
