@startuml
skinparam ArrowFontStyle plain
skinparam FontColor White
hide footbox
skinparam sequenceMessageAlign center

box "Logic" #C8C8FA
participant "<color #white>:LogicManager</color>" as LogicManager #MediumBlue
participant "<color #white>:AddressBookParser</color>" as AddressBookParser #MediumBlue
participant "<color #white>:ViewCommandParser</color>" as ViewCommandParser #MediumBlue
participant "<color #white>vc:ViewCommand</color>" as ViewCommand #MediumBlue
participant "<color #white>r:CommandResult</color>" as CommandResult #MediumBlue
end box

[-> LogicManager : execute("view [INDEX]")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("view [INDEX]")
activate AddressBookParser

create ViewCommandParser
AddressBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> AddressBookParser
deactivate ViewCommandParser

AddressBookParser -> ViewCommandParser : parse("[INDEX]")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser :
deactivate ViewCommand

ViewCommandParser --> AddressBookParser : vc
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> AddressBookParser
destroy ViewCommandParser

AddressBookParser --> LogicManager : vc
deactivate AddressBookParser

LogicManager -> ViewCommand : execute(m)
activate ViewCommand

create CommandResult
ViewCommand -> CommandResult
activate CommandResult

CommandResult --> ViewCommand
deactivate CommandResult

ViewCommand --> LogicManager : r
deactivate ViewCommand

deactivate LogicManager
@enduml
